### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by santiyounger** [jplattel/obsidian-clipper#1]
Hey Joost,

**Thank you so much for making it available on firefox.**

I had a couple of **issues getting it to work**

---

Just went through the process of enabling firefox developer permissions as explained here:
 https://www.thewindowsclub.com/allow-unsigned-extensions-installed-firefox

I set "xpinstall.signatures.required" to false

but it still didn't work, it kept showing the message of not autorized extension 
(This must be an issue on my side)

---

# Temporary Upload
I was able to load the extension temporarily from here:

about:debugging
‘Load Temporary add-on’ where I loaded the file obsidian-clipper > build > firefox > obsidian_clipper.zip

This way I was able to test it out

**I went through the instructions**
I got to the place where I need to set the vault, file name to store notes and saved the settings.

---

Finally when I try to use the extension. 

I selected some text and clicked on the extension, a new tab opens for 1 second and then closes without any further results. If I try again I get the same failed results.

# My Specs

I'm using Firefox in Manjaro Arch Linux
I'm still setting up my obsidian URI so I thought there might have been an issue with that.

Then I tried it on a mac, from firefox at first
and ultimetly just to see if there was a firefox issue, I tried it all again from Google Chrome just to test, but it still didn't work for me.

---

There might me something wrong from my side, I can try it in a couple of days after I've tested Obsidian URI a bit more. (that's what I suspect might be my problem)

Again I really appreciate the help, and I'll keep testings things out

**Comment by jplattel** [comment]
@santiyounger Thanks for the detailed issue report! I think the issue is due to the fact of the combination of linux with Firefox.  I only tested it on Mac OS X and that worked for me. 

As for the [Obsidian url](obsidian://), if you try it manually it should open Obsidian with a message showing that the vault is not found. Does that work? Otherwise it might be a registration error of the protocol by the flatpack app or something...

**Comment by santiyounger** [comment]
thanks @jplattel for taking a look at it. I'll be doing more tests with Mac and then I'll try to move the same set up to linux to see if it works!

Thanks for the help! exciting to see this project grow
