### ISSUE TITLE
clip placeholder seems not working in the latest release

### ISSUE THREAD

**Issue by einverne** [jplattel/obsidian-clipper#10]
First, thank you for providing such a great tool.

The problem I met is that when I set following clip format:

```
{clip}

Clipped from [{title}]({url}) at {datetime}.
```

And clip this project home page in GitHub,  I can't get the content in `clip`. I only got:

```
Clipped from [jplattel/obsidian-clipper: A Chrome extension that easily clips selections to Obsidian](https://github.com/jplattel/obsidian-clipper) at 2021-04-09 14:01:34.
```

By the way, I'm using it under Linux and with Chrome (Version 89.0.4389.90 (Official Build) (64-bit)) and lastest Obsidian.

**Comment by jplattel** [comment]
The clipper doesn't clip an entire page, but just a selection. If no selection is set it defaults to an empty clip (that's what you are seeing). 

Some feedback that you will need to select would be nice to have, I'll look into it :)

**Comment by einverne** [comment]
Oh, thank you for such a quick response. I misunderstand the default behavior. I used to use an extension called markdown-clipper, its default behavior is to clip the entire page.
