### ISSUE TITLE
Error "unrecognized manifest key" in Chrome

### ISSUE THREAD

**Issue by danawhittle** [jplattel/obsidian-clipper#11]
While it is working for me, when doing manual installation as instructed here, I get this error in Chrome - "unrecognized manifest key".

![Screen Shot 2021-04-30 at 12 33 02](https://user-images.githubusercontent.com/3432470/116726253-06018300-a9b1-11eb-8e1c-ed57d9d01af4.jpg)

; )

**Comment by jplattel** [comment]
This key is meant for deployment in Firefox, sadly Chrome is complaining about it but for no reason really... 

The plugin still works! :)
