### ISSUE TITLE
Feature request: ability to clip screenshots

### ISSUE THREAD

**Issue by that0n3guy** [jplattel/obsidian-clipper#12]
I've been using onenote for years and slowly going to obsidian.   One notes screen clipper is pretty fancy.   One thing it allows me to do is clip screenshots and type notes.

Here is an example:
![image](https://user-images.githubusercontent.com/113870/117824606-3f00e980-b234-11eb-8e23-ee840b008310.png)

Is something like this possible?

**Comment by jplattel** [comment]
I'm afraid that's stretching it too far on the way the current plugin is working internally. What I could suggest doing is taking a screenshot after clipping and dragging that into newly created note. It's not the same functionality in one click, but it get's you the closest of what you want :)

For now I'll close this issue as it's not possible but I'll do mark it as an enhancement so I can have a look at it if I decide to rebuild the plugin!
