### ISSUE TITLE
windows's chrome cant get the content

### ISSUE THREAD

**Issue by 0xtaosu** [jplattel/obsidian-clipper#14]
hey bro ! My system is window 10 and I have test obsidian-clipper .

- When I download the plugin from [chrome store](https://chrome.google.com/webstore/detail/obsidian-clipper/mphkdfmipddgfobjhphabphmpdckgfhb?hl=en) and then config , I cant get the content when I select the content and click obsidian-clipper icon .
- When I download the plugin from github and install it , I can get then content . However , when I select the content and click obsidian-clipper icon ,  it will open a new chrome tag but shutdown it quickly .

**Comment by loopernow** [comment]
> * When I download the plugin from github and install it , I can get then content . However , when I select the content and click obsidian-clipper icon ,  it will open a new chrome tag but shutdown it quickly .

Workaround - paste this URL into your address bar (using your own vault name and note name as defined in the extension's settings):

https://jplattel.github.io/obsidian-clipper/clip.html?vault=Obsidian&note=Chrome%20Clippings

This time the tab will not close, and you will have time to click the box to allow the extension to do its thing.

**Comment by ArmandXiao** [comment]
> > * When I download the plugin from github and install it , I can get then content . However , when I select the content and click obsidian-clipper icon ,  it will open a new chrome tag but shutdown it quickly .
> 
> Workaround - paste this URL into your address bar (using your own vault name and note name as defined in the extension's settings):
> 
> https://jplattel.github.io/obsidian-clipper/clip.html?vault=Obsidian&note=Chrome%20Clippings
> 
> This time the tab will not close, and you will have time to click the box to allow the extension to do its thing.

Now the clipper is able to open a `XXX.md` in Obsidian; however, the content won't be written into `XXX.md`. It only copies the content to my clipboard.

Is there a way to let the clipper write the HTML or Markdown into the note automatically?

**Comment by jplattel** [comment]
@IVIJL good idea, I'll add it to the readme. I'm also looking into better feedback on the user side when a clipping is done successfully.

**Comment by loopernow** [comment]
By the way, pretty sure this behavior only occurs on Microsoft Edge. If I remember correctly, the tab that disappears is a security permissions tab of some kind. It's been a while since I figured out the workaround, but what I recall is that on Chrome the tab doesn't close--it stays open allowing you to make a one-time choice to allow whatever it was asking you if you wanted to allow.

**Comment by IVIJL** [comment]
Thats not true for me, I had problems with google chrome.

út 9. 11. 2021 v 18:29 odesílatel loopernow ***@***.***>
napsal:

**Comment by elifiner** [comment]
> * When I download the plugin from github and install it , I can get then content . However , when I select the content and click obsidian-clipper icon ,  it will open a new chrome tag but shutdown it quickly .
> 
> Workaround - paste this URL into your address bar (using your own vault name and note name as defined in the extension's settings):
> 
> https://jplattel.github.io/obsidian-clipper/clip.html?vault=Obsidian&note=Chrome%20Clippings
> 
> This time the tab will not close, and you will have time to click the box to allow the extension to do its thing.

I also needed to go to chrome://flags, search for "Insecure origins treated as secure" and add https://jplattel.github.io as a trusted origin. Otherwise Chrome doesn't display the checkbox that will always open Obsidian for `obsidian://`.

Those two things together got it to work on my system (Chrome  95, MacOS 10.15 Catalina).

**Comment by jroachgit** [comment]
Hi there,
When selecting the text, and then hitting the extension, I get an error, saying "Error: URI too long"
If I don't select ANY text on a webpage and click the extension, a new note is created as expected.

**Comment by jplattel** [comment]
@jroachgit the bug you talk about is #20, I'm currently not able to fix it. I'm actively looking for work-arounds but haven't found any (yet!)

**Comment by wlai-lp** [comment]
If test config works but the extension button doesn't capture content, then it might be a filename issue.  i followed the youtube tutorial and tried to clip a medium article, [link](https://mjplitnick.medium.com/deep-dive-time-to-end-the-two-state-gatekeeping-e974ea3fe390)
it generated the following text for file name, which I determined it was the "|" that prevented obsidian from creating the file
```
Deep%20Dive%20Time%20To%20End%20The%20Two-State%20Gatekeeping%20|%20by%20Mitchell%20Plitnick%20|%20Feb,%202022%20|%20Medium-2022-02-10
```
there are some special characters that's not allowed in filename, | is 1 of them.

**Comment by jplattel** [comment]
@wlai-lp, that's a good find! I'll run a check on what characters are allowed in the note title and strip the rest, that way it's usable. (it can still clip the characters in the note body since all chars are allowed there!)

I'll include this is a next release!

**Comment by Kayfum** [comment]
> > * When I download the plugin from github and install it , I can get then content . However , when I select the content and click obsidian-clipper icon ,  it will open a new chrome tag but shutdown it quickly .
> 
> Workaround - paste this URL into your address bar (using your own vault name and note name as defined in the extension's settings):
> 
> https://jplattel.github.io/obsidian-clipper/clip.html?vault=Obsidian&note=Chrome%20Clippings
> 
> This time the tab will not close, and you will have time to click the box to allow the extension to do its thing.

I find this box:
![image](https://user-images.githubusercontent.com/95751083/156196527-9dc2f1ef-4cba-470e-b37c-c85cf943cad2.png)
:(

**Comment by sideone** [comment]
> > > * When I download the plugin from github and install it , I can get then content . However , when I select the content and click obsidian-clipper icon ,  it will open a new chrome tag but shutdown it quickly .
> > 
> > 
> > Workaround - paste this URL into your address bar (using your own vault name and note name as defined in the extension's settings):
> > https://jplattel.github.io/obsidian-clipper/clip.html?vault=Obsidian&note=Chrome%20Clippings
> > This time the tab will not close, and you will have time to click the box to allow the extension to do its thing.
> 
> I find this box: ![image](https://user-images.githubusercontent.com/95751083/156196527-9dc2f1ef-4cba-470e-b37c-c85cf943cad2.png) :(

Replace 'vault=Obsidian' with the name of your Vault

**Comment by jplattel** [comment]
Closing this as the new version should now save the settings before testing, as well as keeping the test tab open to confirm any dialogs or errors that pop up!

**Comment by ksdavidc** [comment]
Let me add that to this:
> I also needed to go to chrome://flags, search for "Insecure origins treated as secure" and add https://jplattel.github.io as a trusted origin. Otherwise Chrome doesn't display the checkbox that will always open Obsidian for `obsidian://`.

Doing this did not work by itself. However, I discovered the link was in my history, and if I went back, this time it did stop and show the open dialog. There was an option to always open such links, and that worked for me.

**Comment by fritzp6** [comment]
I'm running Brave on KDE Neon. Things were working fine, then something changed, now your plugin is broke. (I know...usual story). After clipping a selection, I click on the Obsidian Clipper icon, I get a new empty note. In settings, if I set the note title to {title} I get only the first word of the title, but still no data in the note. I get the same results whether I use settings to have plain text or markdown. I tried your troubleshooting tips and get no errors that I can find. I just keep getting empty notes.

**Comment by gabb0z** [comment]
Hello!
Running MacOS Ventura.

Plugin works fine with Chrome. In opera though, for some reason the test works, but the plugin doesn't work on websites.

When I run the test command from the extension page:
![image](https://user-images.githubusercontent.com/47632191/207322012-28a1f2da-edd4-441c-97ed-e5854625794c.png)

When I try to clip something:
![image](https://user-images.githubusercontent.com/47632191/207322196-24f38be0-4567-4188-bcdb-16b8fc9b88c9.png)

It seems that when I try to use the extension on a web page, background.js:28 is not loaded

**Comment by mrmarkgithub** [comment]
Hello,

On Win10, using Chrome and Brave. After changing the Options to my liking in both browsers, I clicked to save the vault and note configuration. Then I clicked the "Test configuration" button. It works like a charm in both browsers!

_However_, I cannot get any other page to work! What infos can I get you to assist in troubleshooting? (I am a tech guy but not a coder.)

I have followed all of the troubleshooting steps I could find. (Please feel free to forward a list and I will try them all again.)

1. obsidian:// ... is opening Obsidian on my Win10 machine.
2. https://jplattel.github.io/obsidian-clipper/clip.html ... Generates this error message in both browsers: ![Obsidian Clipper Error A](https://user-images.githubusercontent.com/121066571/208546008-0fc49404-c1dd-482d-9219-1071ebc6f5b6.jpg)
_Full Text of Dialog Box:_
> [Window Title]
> Error
> 
> [Main Instruction]
> Vault not found
> 
> [Content]
> Unable to find a vault for the URL obsidian://new/?vault=obsidian&file=Chrome%20Clippings&append=true&content=Unable%20get%20contents%20of%20the%20clip
> 
> [OK]

3. https://jplattel.github.io/obsidian-clipper/clip.html?vault=<MainVault> ... Generates this error message in both browsers:
![Obsidian Clipper Error B](https://user-images.githubusercontent.com/121066571/208546566-8ee1f657-4bfd-44b0-98de-3dbdcd7ad5ef.jpg)
_Full Text of Dialog Box:_

> [Window Title]
> Error
> 
> [Main Instruction]
> Vault not found
> 
> [Content]
> Unable to find a vault for the URL obsidian://new/?vault=%3Cvaultname%3E&file=Chrome%20Clippings&append=true&content=Unable%20get%20contents%20of%20the%20clip
> 
> [OK]

It looks to me like the value <vaultname> is not properly being replaced with the actual vault name; I have only 1 vault: "MainVault".

What else can I try? How else can I be of help?

Regards,

Mark

**Comment by Ches-ctrl** [comment]
Any help on this error?
![image](https://user-images.githubusercontent.com/65985457/212839897-ea38bc62-b155-4d3b-8f95-d379858a895e.png)

**Comment by chrischung3** [comment]
Hi, when I finished configuring, the "Test Configuration" would be successful. But this happened when I tried to clip it with the extension:

https://github.com/jplattel/obsidian-clipper/assets/51731694/d53340c7-45f8-4688-932d-3601779cbdf5
