### ISSUE TITLE
Zettelkasten id miss zeros

### ISSUE THREAD

**Issue by bborysenko** [jplattel/obsidian-clipper#16]
The placeholder `{zettel}` does not match the Obsidian default format. For example file created at 2021-09-25 22:42:34 has id 2021925224234 instead of 2021`0`925224234.

It would be great if placeholder has at least the full format with zeros. Or even better, has option to customize format.

**Comment by jplattel** [comment]
Good catch! I’ll fix this in the next release :)

**Comment by jplattel** [comment]
This is fixed in [0.3.0](https://github.com/jplattel/obsidian-clipper/releases) :)
