### ISSUE TITLE
Links in wikipedia.

### ISSUE THREAD

**Issue by joezhouchenye** [jplattel/obsidian-clipper#19]
Links in Wikipedia are not handled well. For example,  `[speech bubbles](https://en.wikipedia.org/wiki/Speech_balloon "Speech balloon")` is expected, but actually  `[speech bubbles](/wiki/Speech_balloon "Speech balloon")` is copied. This will result in empty nodes in the relationship graph and if clicked accidentally, a folder called wiki and empty files will be created.
Also, citations are annoying, since they are meaningless with expressions like `[\[2\]](#cite_note-2)`.

**Comment by joezhouchenye** [comment]
When I directly copy and paste into obsidian, everything is what I expected. I am starting to think why should I ever use this plugin...

**Comment by jplattel** [comment]
This is a problem with the html parser that doesn't resolve relative links at this moment. I'm looking into the problem, but haven't found a solution yet.. 

I will close this issue and you can follow on #7 as that is the main issue that I'll be using post updates :)
