### ISSUE TITLE
The chrome extension is not working

### ISSUE THREAD

**Issue by DataSciLearner** [jplattel/obsidian-clipper#2]
I see that you have a chrome extension for this tool now. https://chrome.google.com/webstore/detail/obsidian-clipper/mphkdfmipddgfobjhphabphmpdckgfhb

I specified the vault in options. But when I click on the extension after selecting any web content, a quick flash of a tab appears and disappears. Then nothing happens. No content is saved either.

**Comment by DataSciLearner** [comment]
Issue 1:
The extension is still not opening the vault. I did the following steps. 
1. Set the name of the vault and note that I'd created in my drive in the settings page.
2. Typed obsidian:/ in the address bar which brought up the allow application dialog to open Obsidian, wherein I selected the vault. (Note: obsidian:// gives error, but obsidian:/ goes through and opens the application.)
3. I then opened a webpage, selected content and clicked on extension.
A new tab briefly comes and goes, and then nothing happens after this. The extension is not automatically opening Obsidian vault, which I believe it should do as per your description?!
OTOH, If I manually open obsidian, I can paste the selected content with the source url. 

Issue 2:
Also, in the pasted content, the first line is always showing up as a quote with a preceding ">"; even though the original web content doesn't have the ">".

**Comment by jplattel** [comment]
@DataSciLearner thanks for the details feedback! 

It's strange that with just one `/` it seems to work, but not with `//`. I will have to look into that, on what OS are you on? 

For the second issue, you can configure the blockquote through Clipping format in the extension settings as well, if you remove it there it should not show up in the pasted contents :)

**Comment by DataSciLearner** [comment]
> @DataSciLearner thanks for the details feedback!
> 
> It's strange that with just one `/` it seems to work, but not with `//`. I will have to look into that, on what OS are you on?
> 
I think it probably is interpreting // as ///. 
When I enter  obsidan://, it gives an error dialog box saying "vault not found, unable to a vault for the url obsidian:///". With obsidan:/, it goes through. 
Yet, the issue is that when I select a content and click on the extension nothing happens (just a tab appears and disappears for a brief second). I have to manually open obsidian and paste it. (Have set up the vault in options as per instructions).

> For the second issue, you can configure the blockquote through Clipping format in the extension settings as well, if you remove it there it should not show up in the pasted contents :)
This has resolved it. 
Thanks very much for this tool. 
I was using MarkDownload extension before, but your Obsidian Clipper is better for two reasons. 
1. With MarkDownload, after having scrolled through the webpage to highlight, I had to scroll through the markdown again to select the relevant content to copy. With Obsidian Clipper, I can create the clipping just as I scroll through the webpage.
2. I like that along with the provenance url, the pasted content also has the timestamp. This makes it so suitable for zettlekasten notes.

**Comment by cocoonkid** [comment]
I cannot get it to work either. Linux (Arch) and Brave Browser here. I'd love this to work ;-)

This is an awesome contribution and I will follow up with suggestions.
But in general it would be great to copy features from the raindrop.io web clipper.

**Comment by jplattel** [comment]
@cocoonkid Are you running the flatpak install of Obsidian? There's a known issue with the other install methods not working correctly with the `obsidian://` protocol.

As for the clipper from raindrop.io, I'll have a look! 👍

**Comment by cocoonkid** [comment]
Thank you for the swift reply.

No, I am using the installation via aur repository.  But today I found that after reboot the connection seems to work.

But it only "opens" the note but does not add anything.

**Comment by jplattel** [comment]
@cocoonkid it's expected behavior, since a Chrome extension cannot do an action beyond Chrome itself. Therefore you must paste the contents manually (it is copied to your clipboard).

This is solvable on OSX with Keyboard Meastro or AutoHotKey on Windows, but I have not experience with linux automation on this part. 

Once Obsidian allows actions for URL-scheme's it can be done automatically, but there is not timeline for that yet...

**Comment by cocoonkid** [comment]
Understood! Thanks so much.
