### ISSUE TITLE
iCloud folder navigation

### ISSUE THREAD

**Issue by jimpfaff** [jplattel/obsidian-clipper#22]
I have my Obsidian files in my iCloud folder to allow for sync to iOS Obsidian app. I attempted placing the file path in the Options settings, but it doesn't seem to work. 

This plugin would be very helpful to me. But I must use iCloud to get the functionality I need for the iOS app.

**Comment by jplattel** [comment]
The file path is relative within the Vault, so if you specify the correct vault name it should clip to it to the folder specified. Sorry that it's confusing! I think I could better name it as `folder` instead of `path`. Could you let me know if that works for you? Thanks ✌️

**Comment by jimpfaff** [comment]
It doen't it seems because it's looking for a relative path to the Documents folder in the Mac where Obsidian natively sets the folder to appear......I think. I've attempted to use direct path navigation as i would in the terminal before the name of the Obsidian repository, and that doesn't seem to work.

**Comment by vanrado** [comment]
Hi there,
I also tackled with this iCloud related problem. For the Vault name I entered ```iCloud~md~obsidian``` and it solved the problem with ```Vault not found error```. Pls @jimpfaff can you check that, if it works on your side too?

**Comment by jimpfaff** [comment]
@vanrado That didn't work. I have addressed the directory in other ways with "~/Library/Mobile\ Documents/com~apple~CloudDocs/Obsidian/". It works in the terminal and I can address other folders in the iCloud folder. I attempted what you requested. And I attempted to use that specific addressing in the clipper using the above going into the Obsidian folder adding the subfolder I have set up there. It just doesn't seem to work any way I can find.

**Comment by jimpfaff** [comment]
Ok.....so hold on a second. Suddenly when I input the folder name I have in my iCloud folder, it is linking it. Yes. It's suddenly working. 

Just a note here. It would be nice to create a new note into a specified folder. I'll take a look at the code and see what I might be able to work up on my own.

**Comment by Jiangchanglong1991** [comment]
@jimpfaff I have the same issue, what did you put in the Vault section to make it work?  I put Obsidian which is both my Vault name and the folder's name inside my iCloud folder.
