### ISSUE TITLE
Any possibility of adding the website's 'main' image to the clip template?

### ISSUE THREAD

**Issue by jurassicparkin** [jplattel/obsidian-clipper#23]
Thanks for this extension, it's awesome!

I was wondering if there's any way to receive the 'main' image from a website (e.g. similar to sites like Pocket), and place the image URL in my template using { } brackets?
I tried {og:image} but had no luck.
The reason I ask, is I'm wanting to organize notes in dataview tables in a similar way to Pocket.
I have my table set up and working with images, but it would be amazing if the image URL was grabbed automatically for me :-)

Also, while Googling I came across [Image Resolver](http://mauricesvay.github.io/ImageResolver/), which helps find the 'main' image from a website. I wonder if this could be implemented somehow?

Thanks :-)

**Comment by jplattel** [comment]
Getting the `og:image` and have that usable in the template might be possible. I'll have a look for the next release to get this to work :)

**Comment by jurassicparkin** [comment]
Awesome! 😊 Thanks for looking into it.

**Comment by jplattel** [comment]
This is now implemented! You can use {og:image} in the note template if you have [release 0.3.4](https://github.com/jplattel/obsidian-clipper/releases/tag/0.3.4)! 🍻

**Comment by jurassicparkin** [comment]
Thanks so much for implementing this! I'm getting some great use out of it! :-D

Do you know how I'd go about setting a default image size? Or is that a whole other problem?

Thanks again, much appreciated :-)
