### ISSUE TITLE
use chrome extension now

### ISSUE THREAD

**Issue by uwe999** [jplattel/obsidian-clipper#24]
I first tried to install the bookmarklet but didn't get it to work.
The chrome extension https://chrome.google.com/webstore/detail/obsidian-clipper/mphkdfmipddgfobjhphabphmpdckgfhb/related?hl=en didn't work either until I fixed a few things:
- I guess I didn't confirm the "save vault and configuration" 
- I then confirmed with the default "obsidian" vault but my vault is named "Obsidian".
- images didn't get clipped until I checked the "Clip html as markdown" option

Is there still a reason to install it manually from here instead from the chrome web store?

thanks

**Comment by jplattel** [comment]
The Chrome extension is currently up to date with this repository. If you want alpha/beta testing you could use this repository since I'll be releasing it through here first before uploading to the Chrome Web Store :)
