### ISSUE TITLE
can't build this extension on my chrome

### ISSUE THREAD

**Issue by elf7979** [jplattel/obsidian-clipper#25]
Thanks for building amazing extension.

I tried to build but it showed me this error message:

Unrecognized manifest key 'applications'.

   "applications": {
        "gecko": {
            "id": "j@jplattel.nl",
            "strict_min_version": "53.0"
        }

I appreciate it if you enlighten me on this thing.

**Comment by jplattel** [comment]
You could delete this key in the `manifest.json` file, but if you are using [web-ext](https://github.com/mozilla/web-ext) to build it should build it without any problems (only give a warning).

**Comment by jplattel** [comment]
Closing this since it's a warning and builds nonetheless. It's also easy to remove the key (but this breaks the builds for Firefox). 

In the future I might tinker around with `jq` to solve this dynamically..
