### ISSUE TITLE
[feature] More format options for {date} placeholder

### ISSUE THREAD

**Issue by approximate** [jplattel/obsidian-clipper#3]
First off, thanks for the great extension!

I would like to have a possibility to define the format for the `{date}` placeholder. I usually don't need the actual time, and the date (that is, `YYYY-MM-DD`) is enough. Obsidian itself supports this by using a 3-rd party library, so maybe it's possible to implement the same formatting in the extension as well?

**Comment by jplattel** [comment]
Hey @approximate , thanks for the feedback! I will add it to the backlog and keep you update! Supporting a template within this tag shouldn't be that difficult to implement :)

**Comment by jplattel** [comment]
Hey @approximate, I've created a new release that replaces the {date} placeholder to only use the date, and a new placeholder {datetime} that uses date + time, you'll find it here: https://github.com/jplattel/obsidian-clipper/releases/tag/v0.1.2 :)

**Comment by approximate** [comment]
Yes, this works as described, thanks a lot!
