### ISSUE TITLE
New clipping in dedicated folder

### ISSUE THREAD

**Issue by Wolfi-evo** [jplattel/obsidian-clipper#33]
I would like to send the clippings in a dedicated folder, similar to the standard folder for new notes.

**Comment by jplattel** [comment]
You can specify the folder in the note config, like so: 

<img width="969" alt="Screenshot 2022-01-30 at 15 17 35" src="https://user-images.githubusercontent.com/517775/151704620-78055759-6063-47b3-8af9-ee46b174003c.png">

The interface can be more clear, so I'll add a better description in a future update :)

**Comment by Wolfi-evo** [comment]
I tried similar things in the vault input, but obviously did not succeed. Would not have figured out this solution, so some description would help :-)
