### ISSUE TITLE
Clipping won't work

### ISSUE THREAD

**Issue by RenaudSav** [jplattel/obsidian-clipper#34]
Hi, I'm not a developper, I don't speak HTML, and I try to use Obsidian clipper. 
I created from obsidian a vault named Obsidian Chrome Clippings.
When clicking on the Chrome extension (on Mac), I get the following message from Obsidian :
"Vault not found
Unable to find a vault for the URL obsidian://new?vault=obsidian&file=Chrome%20Clippings&content=%3E%20This%20is%20an%20example%20clip,%0A%0AClipped%20from%20%5BObsidian%20Clipper%5D(https://jplattel.github.io/obsidian-clipper/)%20at%202022-01-30."

What should I do ?

Screen captures :
https://www.dropbox.com/t/6MalApJCmTMR0C7P

**Comment by jplattel** [comment]
The vault should named `obsidian`, the note it clips t is called `Chrome Clippings` by default. You don't have to create a seperate vault, but you can change the names of the note or vault through the settings of this plugin :)
