### ISSUE TITLE
Note title's date value is incorrect

### ISSUE THREAD

**Issue by jroachgit** [jplattel/obsidian-clipper#38]
Hi,

my 'note to clip to' is : 000 Inbox/{zettel} {title}

Clipping format:
> {clip}

Clipped from [{title}]({url}) at [[{date}]] {datetime}

Date format: YYYYMMDD

Datetime format: YYYY-MM-DD HH:mm:ss 

----
I just did a test clip, and the note title is:

202227231451

but it should be
20220207231451 -- that is: 2022-02-07 23:14:51

While my zettle template & plugin completes the file format as: 20220207231819 (which is correct).

Any suggestions?

**Comment by jplattel** [comment]
Are you using the [Chrome Webstore version](https://chrome.google.com/webstore/detail/obsidian-clipper/mphkdfmipddgfobjhphabphmpdckgfhb?hl=nl)? A new one is being reviewed that should fix this issue :)

**Comment by jroachgit** [comment]
Yes, I am.
I believe it has been updated. But, it has a new issue. 

I'll open a new issue specifically.
