### ISSUE TITLE
Handle space character in Note name

### ISSUE THREAD

**Issue by inputsh** [jplattel/obsidian-clipper#4]
So my notes should go to a path that contains spaces: `00 Inbox/Inbox`.

When testing the config, I try to open: `clip.html?vault=Notes&note=/00 Inbox/Inbox`, as it should, but Obsidian throws `File "00" not found`.

I've tried to configure the path without URL encoding (`00 Inbox/Inbox`) and with URL encoding (`00%20Inbox/Inbox`), but the end result is the same.

Using the Firefox version if it makes any difference. Help would be appreciated!

**Comment by jplattel** [comment]
Is the note just called 'Inbox'? In that case it might work if you try just the name of the note instead of the full path :)

**Comment by Dranion** [comment]
Just for reference, what worked for me was copying the full obsidian url: 
> obsidian://open?vault=Default&file=20-29%20%20Nonfiction%20Sources%2F26%20Websites%2FClippings%2FClipping
and then removing it down to just file 
> 20-29%20%20Nonfiction%20Sources%2F26%20Websites%2FClippings%2FClipping
I'm also using the FIrefox version, so I'm surprised the URL encoding didn't work for you. Maybe since you left the slash i? 
What I actually ended up using was this 
> 20-29%20%20Nonfiction%20Sources%2F26%20Websites%2FClippings%2F{date}%20{title}
which accurately goes where I want it to go

**Comment by jplattel** [comment]
Mmh, I need to investigate a bit more it seems :)

I'll dive into when I have time to draft a new release, thanks for the additional information! 👍

**Comment by jplattel** [comment]
Alright it took a while, but this is fixed in the 2.3 release: https://github.com/jplattel/obsidian-clipper/releases/tag/2.3
