### ISSUE TITLE
Check for existing file & add comment

### ISSUE THREAD

**Issue by username-8** [jplattel/obsidian-clipper#41]
when i select create a new file i.e automatic option... it keeps making new files with the same name like 

```
{date}
{date} 1
{date} 2
```

is there a way to make if check if said file already exists & if so.. add the highlight to the next /last line without creating a new file  ???

----
also, it would be great if i can,
- select which note the highlight goes into each time, without having to open obsidian... like Zotero addon. 
- add a comment to the highlight while i'm at it

**Comment by jplattel** [comment]
In the new release [0.5.0](https://github.com/jplattel/obsidian-clipper/releases/tag/0.5.0) it's now possible to append to a note that already exists (if the clip to new note is unchecked). 

Selecting which note isn't currently possible through the obsidian url handler... If the functionality might be possible in the future I'll have a look at it again!
