### ISSUE TITLE
Using {title} in filename won't save on illegal filenames.

### ISSUE THREAD

**Issue by willow512** [jplattel/obsidian-clipper#45]
**Describe the bug**
When I set "clippings/{date}-{title}" as the note to clip to some sites will allow me to save some won't.

**To Reproduce**
1. Set "clippings/{date}-{title}"  in note to clip to
2. Go to a site with a title that would form an illegal filename (My example used | ) (Spinaziesoep met kokosmelk recept - Allerhande | Albert Heijn) 
3. Hit that purple clip button.

**Expected behavior**
I suggest offering a {title} variant intended for the filename which sanitizes the filename.

**Comment by jplattel** [comment]
In the most recent version it should strip those characters! Closing this as it's fixed. Feel free to open a new one if it persists!

**Comment by cemkaan** [comment]
{title} does not work with illegal charracters.  I want to help filtering title input.

```
 < (less than)
  > (greater than)
  : (colon - sometimes works, but is actually NTFS Alternate Data Streams)
  " (double quote)
  / (forward slash)
  \ (backslash)
  | (vertical bar or pipe)
  ? (question mark)
  * (asterisk)
```
