### ISSUE TITLE
Insider Version

### ISSUE THREAD

**Issue by Quorafind** [jplattel/obsidian-clipper#5]
Hey, obsidian's insider version is able to add new note by using URI now. You can check its document here: https://help.obsidian.md/Advanced+topics/Using+obsidian+URI#Action+new . Would be nice to see your plugin to be updated!

**Comment by jplattel** [comment]
Yes, I've just looked at it, I might be able to roll out an update today! Keep you posted!

**Comment by jplattel** [comment]
@Quorafind I've just released 2.0.0, this version includes the new note creation, but somehow line-breaks aren't picked up by the decoder of Obsidian. I will update it once that's done, but I wanted to release this for testing as well :)

**Comment by jplattel** [comment]
Alright, I fixed the newlines thing, I did delete the 2.0.0 since it's not versioned correctly, sorry about that! The latest release https://github.com/jplattel/obsidian-clipper/releases/tag/0.2.1 allows you to clip to a new note with newlines :)
