### ISSUE TITLE
Append to an existing file // add note to selected text (enhancement)

### ISSUE THREAD

**Issue by archelpeg** [jplattel/obsidian-clipper#6]
> In the long term future, maybe even offer the possiblity to search through your notes and append it?

Would it be possible to append the copied text to a predefined note? So to have that as a third option?
Because the Obsidian URI seems to allow the creation of new files, does it also let you append or not?

And perhaps this would be better suited as another issue/feature request:
Would it be possible to have the option to add a note to the selected text before sending it to Obsidian?

**Comment by archelpeg** [comment]
And would it be possible to close the opened tab automatically?

**Comment by jplattel** [comment]
First of, closing the tab should indeed happen, that's a debug thing left by me in the previous release.. I should fix that.

As for appending the note, there's currently not a way to directly support appending. It is however possible to chain several shortcuts with apps like Keyboard Meastro (or any alternative like AutoHotKey on Windows. (unsure of a linux variant exists).

The way it works is that you input a note-name and don't check the box of creating a new note. That way the note specified will open and you can paste the contents of the clipboard (which contains the clip!). Chaining the activation of the chrome plugin + pasting would result in the result you're aiming for I think :)

**Comment by archelpeg** [comment]
Thank you for your answer. :)
I'm on Windows and also use Autohotkey, I'd just have to figure out how to activate the plugin with it.
I think for now I'll just do it manually because automating it, well, I think this describes it best: [xkcd - automation](https://xkcd.com/1319/)

**Comment by jplattel** [comment]
I'm closing this issue as it can be done by chaining shortcuts. Unfortunately the current obsidian url interface doesn't allow for appending notes. If this changes in the future I'll implement it :)
