### ISSUE TITLE
Internal links are stripped of main part of URL

### ISSUE THREAD

**Issue by seb-mm** [jplattel/obsidian-clipper#7]
I also encountered a bug while using the HTML to markdown converter:
When there are links that lead to the same site, they get stripped of the main part of the URL.
`[Rdn. 185](#LKO_09-1_263_mn_185)` is wrong.
`[Rdn. 185](https://www-degruyter-com.docweb.rz.uni-passau.de:2443/document/database/LKO/entry/LKO_09-1_263/html#LKO_09-1_263_mn_185)` is how it should be.

Another example:
`[299](/?typ=reference&y=300&b=1962&s=299&z=GA)` is wrong.
`[299](https://beck-online.beck.de/?typ=reference&y=300&b=1962&s=299&z=GA)` is how it should be.

This doesn't happen with external links, their conversion is as expected. 

I guess the problem with internal links is because the websites use relative links? I'm not exactly  sure how this could be addressed. However, when I copy from the web and paste to markdown in Obsidian, then these internal links get resolved properly.

**Comment by jplattel** [comment]
Hey @archelpeg this is indeed due to the fact that the website uses relative links. I might be able to extend the Turndown service to create a full URL. Will look into that! :)

**Comment by archelpeg** [comment]
Thank you, I'm looking forward to it. :)

**Comment by jplattel** [comment]
I've been tinkering with a plugin for Turndown, but cannot get it to work reliably. 

I'll leave this open for a future reminder to look into again! Sorry for not being able to fix this...

**Comment by huyz** [comment]
@jplattel Might want to check out how https://github.com/laurent22/joplin/blob/dev/readme/clipper.md or https://github.com/webclipper/web-clipper/ does it

**Comment by jplattel** [comment]
This is now fixed in release [0.3.0](https://github.com/jplattel/obsidian-clipper/releases)!
