### ISSUE TITLE
Multi line Clipping format

### ISSUE THREAD

**Issue by baptisteArno** [jplattel/obsidian-clipper#8]
Thank you for this cool extension 👍

I'm setting Clipping format to :
```
> {clip}

---

# Reference
- [{title}]({url})
```

The test note looks like this:
```
> This is an example clip---
```

Is this a bug? I could work on this feature if you'd like.

**Comment by baptisteArno** [comment]
In fact, the bug only happens with the test note.

**Comment by jplattel** [comment]
Yes, it has to do with the way the test clipping is created! Thank you for your feedback, I think I can solve this in the next version! 👍

**Comment by jplattel** [comment]
The 2.3 release fixes this! https://github.com/jplattel/obsidian-clipper/releases/tag/2.3 

Thank you for the bug-report! 👍
