### ISSUE TITLE
Clip a note in an existing folder

### ISSUE THREAD

**Issue by baptisteArno** [jplattel/obsidian-clipper#9]
When setting "Note to clip to" to `<EXISTING_FOLDER>/<NAME>`, the test works great but when I clip an actual site it creates a note at the root of the Vault with the following name: `<EXISTING_FOLDER><NAME>`

**Comment by jplattel** [comment]
Oh, I see, I looked into this and I need to change the way the clipping works by using the path in the protocol handler. Will update this in the next version as well!

**Comment by jplattel** [comment]
This is fixed in 2.3: https://github.com/jplattel/obsidian-clipper/releases/tag/2.3 :)
